library(tidyverse)
library(shinydashboard)
library(data.table)
library(shinyjs)
library(treemap)
library(plotly)
library(dashboardthemes)
library(shinythemes)
library(hrbrthemes)
library(ggthemes)
library(scales)
library(d3treeR)
library(DT)
library(apputils)

library(rjson)
library(RJDBC)
library(janitor)


library(leaflet)
library(sf)

library(rnaturalearth)
library(rworldmap)
library(brazilmaps)
